services:
  logto:
    container_name: idealjs_logto
    image: registry.cn-hangzhou.aliyuncs.com/idealjs/logto:1.30.1
    networks:
      - traefik-network
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:${POSTGRES_PASSWORD-p0stgr3s}@postgres:5432/logto
      - ENDPOINT=https://logto-auth.idealjs.com
      - ADMIN_ENDPOINT=https://logto-admin.idealjs.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logto-auth.rule=Host(`logto-auth.idealjs.com`)"
      - "traefik.http.routers.logto-auth.entrypoints=websecure"
      - "traefik.http.routers.logto-auth.tls=true"
      - "traefik.http.routers.logto-auth.tls.certresolver=idealjs-resolver"
      - "traefik.http.routers.logto-auth.service=logto-auth"
      - "traefik.http.services.logto-auth.loadbalancer.server.port=3001"

      - "traefik.http.routers.logto-admin.rule=Host(`logto-admin.idealjs.com`)"
      - "traefik.http.routers.logto-admin.entrypoints=websecure"
      - "traefik.http.routers.logto-admin.tls=true"
      - "traefik.http.routers.logto-admin.tls.certresolver=idealjs-resolver"
      - "traefik.http.routers.logto-admin.service=logto-admin"
      - "traefik.http.services.logto-admin.loadbalancer.server.port=3002"

networks:
  traefik-network:
    external: true
