services:
  logto:
    container_name: idealjs_logto
    depends_on:
      postgres:
        condition: service_healthy
    image: registry.cn-hangzhou.aliyuncs.com/idealjs/logto:1.24.0
    networks:
      - default-network
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:${POSTGRES_PASSWORD-p0stgr3s}@postgres:5432/logto
    labels:
      - "traefik.http.routers.logto.rule=Host(`auth.idealjs.com`)"
      - "traefik.http.services.logto.loadbalancer.server.port=3001"

  postgres:
    container_name: idealjs_logto_pg
    image: registry.cn-hangzhou.aliyuncs.com/idealjs/postgres:17-alpine3.21
    networks:
      - default-network
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-p0stgr3s}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data:

networks:
  default-network:
    external: true
