services:
  traefik:
    container_name: idealjs_traefik
    image: registry.cn-hangzhou.aliyuncs.com/idealjs/traefik:v3.3.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
