services:
  infisical:
    container_name: idealjs_infisical
    image: infisical/infisical:latest-postgres
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - NODE_ENV=production
      - DB_CONNECTION_URI=postgres://postgres:${POSTGRES_PASSWORD-p0stgr3s}@postgres:5432/infisical
      - REDIS_URL=redis://:${REDIS_PASSWORD-p0stgr3s}@redis:6379/infisical
      - AUTH_SECRET=${INFISICAL_AUTH_SECRET-1nf131cal}
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idealjs-infisical.rule=Host(`infisical.idealjs.com`)"
      - "traefik.http.routers.idealjs-infisical.entrypoints=websecure"
      - "traefik.http.routers.idealjs-infisical.tls=true"
      - "traefik.http.routers.idealjs-infisical.tls.certresolver=idealjs-resolver"
      - "traefik.http.routers.idealjs-infisical.service=idealjs-infisical"
      - "traefik.http.services.idealjs-infisical.loadbalancer.server.port=8080"

networks:
  traefik-network:
    external: true
