services:
  postgres:
    container_name: idealjs_pg
    image: registry.cn-hangzhou.aliyuncs.com/idealjs/postgres:17-alpine3.21
    networks:
      - traefik-network
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-p0stgr3s}
    volumes:
      - database_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: idealjs_redis
    image: registry.cn-hangzhou.aliyuncs.com/idealjs/redis:8.0.1-alpine3.21
    networks:
      - traefik-network
    command: >
      --requirepass ${REDIS_PASSWORD-r3d1s}
    volumes:
      - database_redis_data:/data

volumes:
  database_pg_data:
    external: true
  database_redis_data:
    external: true

networks:
  traefik-network:
    external: true
