name: Deploy Database
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy"
    environment:
      name: idealjs-prod
    steps:
      - uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/tmp.key
          chmod 600 ~/.ssh/tmp.key
          cat >>~/.ssh/config <<END
          Host idealjs.com
            HostName $SSH_HOST
            User idealjs
            IdentityFile ~/.ssh/tmp.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.IDEALJS_ALI_SSH_KEY }}
          SSH_HOST: ${{ secrets.IDEALJS_ALI_SSH_HOST }}

      - name: Create PG Volume
        continue-on-error: true
        run: |
          ssh idealjs.com 'docker volume create database_pg_data'

      - name: Create Redis Volume
        continue-on-error: true
        run: |
          ssh idealjs.com 'docker volume create database_redis_data'

      - name: Start Database
        run: |
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> ~/.tmp.env
          echo "REDIS_PASSWORD=$REDIS_PASSWORD" >> ~/.tmp.env
          ssh idealjs.com 'mkdir -p ~/workspace/database'
          scp ~/.tmp.env idealjs.com:~/workspace/database/.env
          scp ./packages/database/docker-compose.yml idealjs.com:~/workspace/database/docker-compose.yml
          ssh idealjs.com 'docker compose -f ~/workspace/database/docker-compose.yml up -d'
        env:
          POSTGRES_PASSWORD: ${{ secrets.IDEALJS_POSTGRES_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.IDEALJS_REDIS_PASSWORD }}

      - name: Clean
        if: always()
        run: |
          rm ~/.ssh/tmp.key
          rm ~/.tmp.env
