name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - qa

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/home
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - name: Pull Vercel Environment Information
        run: |
          yarn install --immutable
          yarn vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          cp .vercel/.env.preview.local .env
      - name: Build Project Artifacts
        run: yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deploy.log
